# Generated by Django 5.2 on 2025-04-14 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0002_careerinfo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CareerInfo",
        ),
    ]
