# Generated by Django 5.2 on 2025-04-14 08:07

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0003_delete_careerinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerInfo",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="작성일자"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="작성일자"
                    ),
                ),
                (
                    "career_info_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        max_length=20, verbose_name="근무 회사 이름"
                    ),
                ),
                (
                    "position",
                    models.CharField(max_length=20, verbose_name="근무 직책"),
                ),
                (
                    "employment_period_start",
                    models.DateField(verbose_name="입사일"),
                ),
                (
                    "employment_period_end",
                    models.DateField(verbose_name="퇴사일"),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career",
                        to="resume.resume",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
