# Generated by Django 5.2 on 2025-04-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0004_careerinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="careerinfo",
            name="employment_period_end",
            field=models.DateField(null=True, verbose_name="퇴사일"),
        ),
    ]
