# Generated by Django 5.2 on 2025-04-15 02:47

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0006_alter_careerinfo_resume"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resume",
            name="education",
        ),
        migrations.AddField(
            model_name="resume",
            name="education_level",
            field=models.CharField(
                default="", max_length=20, verbose_name="학력 구분"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resume",
            name="education_state",
            field=models.CharField(
                default="", max_length=20, verbose_name="학적"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resume",
            name="job_category",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="직무 분야"
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="resume_title",
            field=models.CharField(
                default="", max_length=20, verbose_name="이력서 제목"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resume",
            name="school_name",
            field=models.CharField(
                default="asd", max_length=20, verbose_name="학교명"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="careerinfo",
            name="employment_period_end",
            field=models.DateField(blank=True, verbose_name="퇴사일"),
        ),
        migrations.AlterField(
            model_name="careerinfo",
            name="position",
            field=models.CharField(max_length=20, verbose_name="직무"),
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="작성일자"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="작성일자"
                    ),
                ),
                (
                    "certification_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="자격증 아이디",
                    ),
                ),
                (
                    "certification_name",
                    models.CharField(max_length=20, verbose_name="자격증 이름"),
                ),
                (
                    "issuing_organizatio",
                    models.CharField(max_length=20, verbose_name="발급 기관"),
                ),
                ("date_acquired", models.DateField(verbose_name="취득일")),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="resume.resume",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
