# Generated by Django 5.2 on 2025-04-18 01:07

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_posting", "0001_initial"),
        (
            "resume",
            "0008_rename_issuing_organizatio_certification_issuing_organization",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="작성일자"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="작성일자"
                    ),
                ),
                (
                    "submission_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "memo",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="지원공고 메모"
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False, verbose_name="기업 담당자 읽음 여부"
                    ),
                ),
                (
                    "job_posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions_job_posting",
                        to="job_posting.jobposting",
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions_resume",
                        to="resume.resume",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
