# Generated by Django 5.2 on 2025-04-19 15:01
import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0009_submission"),
        ("user", "0004_remove_userinfo_wish_work_place_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resume",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="resume",
        ),
        migrations.AddField(
            model_name="submission",
            name="snapshot_resume",
            field=models.JSONField(
                default=dict, verbose_name="지원 시점 이력서 정보"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="submission",
            name="user",
            field=models.ForeignKey(
                default=uuid.uuid4,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions_user",
                to="user.userinfo",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="careerinfo",
            name="employment_period_end",
            field=models.DateField(
                blank=True, null=True, verbose_name="퇴사일"
            ),
        ),
    ]
