# Generated by Django 5.2 on 2025-04-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "resume",
            "0010_rename_user_id_resume_user_remove_submission_resume_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="memo",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="지원공고 메모",
            ),
        ),
    ]
