# Generated by Django 5.2 on 2025-04-16 08:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "city_no",
                    models.CharField(max_length=10, verbose_name="시 고유번호"),
                ),
                (
                    "city_name",
                    models.CharField(max_length=20, verbose_name="시 이름"),
                ),
                (
                    "district_no",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="구 고유번호"
                    ),
                ),
                (
                    "district_name",
                    models.CharField(max_length=20, verbose_name="구 이름"),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PolygonField(
                        srid=5179, verbose_name="구 경계"
                    ),
                ),
            ],
        ),
    ]
