# Generated by Django 5.2 on 2025-04-16 09:39

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="district",
            name="geometry",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                srid=5179, verbose_name="구 경계"
            ),
        ),
    ]
