# Generated by Django 5.2 on 2025-04-17 08:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0002_alter_district_geometry"),
    ]

    operations = [
        migrations.AddField(
            model_name="district",
            name="emd_name",
            field=models.CharField(
                default="a", max_length=40, verbose_name="읍면동 이름"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="district",
            name="emd_no",
            field=models.CharField(
                default="asd",
                max_length=10,
                unique=True,
                verbose_name="읍면동 고유번호",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="district",
            name="city_name",
            field=models.CharField(max_length=40, verbose_name="시 이름"),
        ),
        migrations.AlterField(
            model_name="district",
            name="district_name",
            field=models.CharField(max_length=40, verbose_name="구 이름"),
        ),
        migrations.AlterField(
            model_name="district",
            name="district_no",
            field=models.CharField(max_length=10, verbose_name="구 고유번호"),
        ),
        migrations.AlterField(
            model_name="district",
            name="geometry",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                srid=5179, verbose_name="읍면동 경계"
            ),
        ),
    ]
