# Generated by Django 5.2 on 2025-04-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyinfo",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="is_active",
        ),
        migrations.AddField(
            model_name="commonuser",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
