# Generated by Django 5.2 on 2025-04-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_commonuser_groups_commonuser_is_superuser_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinfo",
            name="wish_work_place",
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="company_logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="company_logos/"
            ),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="certificate_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="certificate_image/"
            ),
        ),
    ]
