# Generated by Django 5.2 on 2025-04-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_remove_userinfo_wish_work_place_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyinfo",
            name="is_staff",
        ),
        migrations.AddField(
            model_name="commonuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
