# Generated by Django 5.2 on 2025-04-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_remove_companyinfo_is_staff_commonuser_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyinfo",
            name="certificate_image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="company_logo",
            field=models.URLField(blank=True, null=True),
        ),
    ]
