# Generated by Django 5.2 on 2025-04-16 06:54

import uuid

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0003_commonuser_groups_commonuser_is_superuser_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="작성일자"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="작성일자"
                    ),
                ),
                (
                    "job_posting_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("job_posting_title", models.CharField(max_length=50)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name="근무지 좌표"
                    ),
                ),
                ("work_time_start", models.DateTimeField()),
                ("work_time_end", models.DateTimeField()),
                ("posting_type", models.CharField(max_length=10)),
                ("employment_type", models.CharField(max_length=10)),
                ("job_keyword_main", models.CharField(max_length=20)),
                ("job_keyword_sub", models.CharField(max_length=20)),
                ("number_of_positions", models.IntegerField()),
                ("education", models.CharField(max_length=20)),
                ("deadline", models.DateTimeField()),
                ("time_discussion", models.BooleanField()),
                ("day_discussion", models.BooleanField()),
                (
                    "work_day",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("salary_type", models.CharField(max_length=10)),
                ("salary", models.IntegerField()),
                ("summary", models.CharField(max_length=50)),
                ("content", models.TextField(null=True)),
                (
                    "company_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_postings",
                        to="user.companyinfo",
                        verbose_name="매니저 ID",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
