# Generated by Django 5.2 on 2025-04-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_posting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="address",
            field=models.CharField(default="기본주소", max_length=50),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="city",
            field=models.CharField(default="기본도시", max_length=10),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="district",
            field=models.CharField(default="기본구", max_length=10),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="deadline",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="work_time_end",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="work_time_start",
            field=models.TimeField(),
        ),
    ]
