# Generated by Django 5.2 on 2025-04-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_posting", "0002_jobposting_address_jobposting_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="town",
            field=models.CharField(default="읍,면,동", max_length=10),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="address",
            field=models.CharField(default="근무지 전체 주소", max_length=50),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="city",
            field=models.CharField(default="시,도", max_length=10),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="district",
            field=models.CharField(default="시,군,구", max_length=10),
        ),
    ]
